#!/bin/bash
set -euo pipefail

# WorktreeCreate hook for vLLM
# Creates a git worktree with build artifacts + Python isolation pre-populated.
#
# Input (stdin JSON):
#   WorktreeCreate: { session_id, transcript_path, cwd, hook_event_name, name }
#   PreToolUse:EnterWorktree: { session_id, cwd, hook_event_name, tool_name, tool_input: {name} }
# Output (stdout): absolute path to the created worktree directory
# All logging goes to stderr.

# ── Read hook input ──
INPUT=$(cat)
WORKTREE_NAME=$(echo "$INPUT" | jq -r '.tool_input.name // .name // empty')
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

[ -z "$WORKTREE_NAME" ] && { echo "ERROR: No worktree name provided" >&2; exit 1; }

MAIN_REPO="${CLAUDE_PROJECT_DIR:-$CWD}"
if [ -z "${CLAUDE_PROJECT_DIR:-}" ] && [ -f "$MAIN_REPO/.git" ]; then
    MAIN_REPO=$(git -C "$MAIN_REPO" rev-parse --path-format=absolute --git-common-dir 2>/dev/null | sed 's|/\.git$||')
fi

WORKTREE_DIR="$MAIN_REPO/.claude/worktrees/$WORKTREE_NAME"

# Resolve the true base repository for shared resources (lock, ccache).
# In a session worktree, MAIN_REPO is the session worktree path, but
# git worktree add operates on the shared base repo. The lock must
# protect that shared resource, not a per-session copy.
BASE_REPO=$(git -C "$MAIN_REPO" rev-parse --path-format=absolute --git-common-dir 2>/dev/null | sed 's|/\.git$||') || true
BASE_REPO="${BASE_REPO:-$MAIN_REPO}"

# Guard: already exists
if [ -d "$WORKTREE_DIR" ]; then
    echo "WARN: Worktree already exists: $WORKTREE_DIR" >&2
    echo "$WORKTREE_DIR"
    exit 0
fi

# ── 1. Create git worktree (with flock for concurrency safety) ──
# Session-namespaced branch naming for cross-session safety
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
if [ -n "$SESSION_ID" ]; then
    BRANCH_NAME="session/${SESSION_ID}/ammo-${WORKTREE_NAME}"
else
    BRANCH_NAME="worktree-${WORKTREE_NAME}"
fi
mkdir -p "$MAIN_REPO/.claude/worktrees"

# Lock in session worktree (writable by session_user), NOT base repo (may be root-owned).
# Cross-session concurrency is handled by git's own internal locking.
LOCKFILE="$MAIN_REPO/.claude/worktrees/.create-lock"
(
    flock -x 200
    echo "Creating worktree '$WORKTREE_NAME'..." >&2
    git -C "$MAIN_REPO" worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR" HEAD 2>&1 >&2 || \
        git -C "$MAIN_REPO" worktree add "$WORKTREE_DIR" "$BRANCH_NAME" 2>&1 >&2 || \
        git -C "$MAIN_REPO" worktree add "$WORKTREE_DIR" HEAD 2>&1 >&2 || {
            echo "ERROR: Failed to create worktree" >&2; exit 1
        }
) 200>"$LOCKFILE"
[ ! -d "$WORKTREE_DIR" ] && { echo "ERROR: Worktree creation failed" >&2; exit 1; }

# ── 2. Copy build artifacts ──
echo "Copying build artifacts..." >&2

# CMakeUserPresets.json (gitignored, needed for cmake --preset)
# Patch in CCACHE_PATH_MAP to remap worktree paths → main repo paths before hashing.
# Combined with CCACHE_BASEDIR=${sourceDir}, this gives 100% cross-worktree cache hits.
if [ -f "$MAIN_REPO/CMakeUserPresets.json" ]; then
    cp "$MAIN_REPO/CMakeUserPresets.json" "$WORKTREE_DIR/" 2>/dev/null
    # Inject CCACHE_PATH_MAP into the environment block
    if command -v jq &>/dev/null; then
        jq --arg pm "$WORKTREE_DIR:$BASE_REPO" \
           '.configurePresets[0].environment.CCACHE_PATH_MAP = $pm' \
           "$WORKTREE_DIR/CMakeUserPresets.json" > "$WORKTREE_DIR/CMakeUserPresets.json.tmp" && \
           mv "$WORKTREE_DIR/CMakeUserPresets.json.tmp" "$WORKTREE_DIR/CMakeUserPresets.json"
    else
        echo "  WARN: jq not found, CCACHE_PATH_MAP not set (builds will be slow)" >&2
    fi
    echo "  CMakeUserPresets.json (with CCACHE_PATH_MAP)" >&2
fi

# All .so files under vllm/ (glob — automatically picks up new extensions)
find "$MAIN_REPO/vllm" -name "*.so" -type f 2>/dev/null | while read so; do
    REL="${so#$MAIN_REPO/}"
    mkdir -p "$(dirname "$WORKTREE_DIR/$REL")"
    cp "$so" "$WORKTREE_DIR/$REL" 2>/dev/null || true
done
echo "  .so files: $(find "$WORKTREE_DIR/vllm" -name '*.so' 2>/dev/null | wc -l) copied" >&2

# _version.py (generated by setuptools-scm, needed for `import vllm`)
[ -f "$MAIN_REPO/vllm/_version.py" ] && \
    cp "$MAIN_REPO/vllm/_version.py" "$WORKTREE_DIR/vllm/_version.py" 2>/dev/null && \
    echo "  vllm/_version.py" >&2 || true

# ── 2b. Copy gitignored runtime Python packages ──
# These are gitignored directories/files that contain Python code needed at
# runtime. Unlike .so files (already handled above), these are pure Python
# but excluded from git by patterns like `vllm/vllm_flash_attn/*` and
# `vllm/third_party/triton_kernels/*`. Without them, `import vllm` fails
# with missing module errors in the worktree.
#
# Uses `git ls-files` to discover ignored files dynamically rather than
# hardcoding paths — stays in sync with .gitignore automatically.
echo "Copying gitignored runtime Python packages..." >&2

COPIED=0
FAILED=0
while IFS= read -r file; do
    mkdir -p "$(dirname "$WORKTREE_DIR/$file")"
    if cp "$MAIN_REPO/$file" "$WORKTREE_DIR/$file" 2>/dev/null; then
        COPIED=$((COPIED + 1))
    else
        echo "  WARN: failed to copy $file" >&2
        FAILED=$((FAILED + 1))
    fi
done < <(git -C "$MAIN_REPO" ls-files --others --ignored --exclude-standard -- \
    'vllm/vllm_flash_attn' 'vllm/third_party' 'vllm/grpc' 2>/dev/null | \
    grep -v '__pycache__')
[ "$FAILED" -gt 0 ] && FAIL_MSG=", $FAILED failed" || FAIL_MSG=""
echo "  $COPIED gitignored runtime files copied${FAIL_MSG}" >&2

# No cmake-build-release/ copying needed — ccache with CCACHE_PATH_MAP (set in
# CMakeUserPresets.json above) provides 100% cross-worktree cache hits.
# The agent runs `cmake --preset release && cmake --build --preset release --target install`
# which takes ~50s configure + ~5s build (all ccache hits) on first use.

# ── 3. Create per-worktree .venv for Python isolation ──
echo "Creating worktree venv..." >&2
PY_VERSION=$("$MAIN_REPO/.venv/bin/python" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
"$MAIN_REPO/.venv/bin/python" -m venv --without-pip "$WORKTREE_DIR/.venv" 2>&1 >&2 && {
    SITE_PKGS="$WORKTREE_DIR/.venv/lib/python${PY_VERSION}/site-packages"

    # Add main venv packages (torch, numpy, etc.) via .pth
    # .pth files added via sys.path do NOT have their .pth files processed,
    # so the main venv's editable install meta_path finder is NOT loaded
    # Main venv site-packages (torch, numpy, triton, flashinfer, xformers, ...) —
    # first line preserves prior direct-dir behavior.
    MAIN_SP="$MAIN_REPO/.venv/lib/python${PY_VERSION}/site-packages"
    echo "$MAIN_SP" > "$SITE_PKGS/main-venv.pth"

    # Materialize AMMO-editable optional GPU/runtime packages into the track venv
    # instead of editing them through the shared session venv. This curated list is
    # intentionally version-sensitive: update it as vLLM adds/removes optional
    # package-backed kernel runtimes.
    #
    # NOTE: precompiled-output packages (flashinfer_cubin ~1.1GB, flashinfer_jit_cache)
    # are intentionally EXCLUDED. They are build artifacts, not an authoring surface,
    # and the materialized `flashinfer` python package still resolves them at runtime
    # via the main-venv.pth fallback (the whole main site-packages is on sys.path).
    # Copying them only burned ~1.1GB of disk + thousands of file-creates per track.
    AMMO_TRACK_LOCAL_RUNTIME_PACKAGES=(
        flashinfer
        nvidia_cutlass_dsl
        deep_gemm
        deepgemm
        flash_mla
        flashmla
        flash_attn
        mamba_ssm
        causal_conv1d
    )
    AMMO_TRACK_LOCAL_RUNTIME_EXTRA_GLOBS=(
        flashinfer_python-*.dist-info
        flash_attn_*.so
        flash_attn*cuda*.so
        selective_scan*.so
        causal_conv1d*.so
    )
    MATERIALIZED_ROOTS_FILE="$SITE_PKGS/.ammo-materialized-runtime-roots"
    : > "$MATERIALIZED_ROOTS_FILE"

    # Copy src -> dst atomically (tmp + mv) so an existing dst ALWAYS means a
    # complete copy. A mid-copy abort (ENOSPC / EACCES) leaves only a .ammo-tmp
    # leftover, never a half-populated dst that the [ ! -e dst ] guard would then
    # skip forever on a repair re-run. Every failure is non-fatal: a failed copy
    # warns and the package simply isn't materialized (champion falls back to the
    # shared copy via main-venv.pth) — it must never abort worktree creation.
    materialize_runtime_path() {
        local src="$1" rel dst tmp
        [ -e "$src" ] || return 0
        rel="${src#$MAIN_SP/}"
        [ "$rel" = "$src" ] && return 0
        dst="$SITE_PKGS/$rel"
        mkdir -p "$(dirname "$dst")" || { echo "  WARN: mkdir failed for $rel" >&2; return 0; }
        if [ ! -e "$dst" ]; then
            tmp="${dst}.ammo-tmp.$$"
            rm -rf "$tmp" 2>/dev/null || true
            if cp -a "$src" "$tmp" 2>/dev/null && mv "$tmp" "$dst" 2>/dev/null; then
                : # complete copy now visible at dst
            else
                echo "  WARN: failed to materialize $rel (using shared copy)" >&2
                rm -rf "$tmp" 2>/dev/null || true
                return 0
            fi
        fi
        if [ -d "$src" ] && [ -d "$dst" ]; then
            printf '%s\t%s\n' "$src" "$dst" >> "$MATERIALIZED_ROOTS_FILE" || true
        fi
        return 0
    }

    shopt -s nullglob
    for package_name in "${AMMO_TRACK_LOCAL_RUNTIME_PACKAGES[@]}"; do
        materialize_runtime_path "$MAIN_SP/$package_name"
        materialize_runtime_path "$MAIN_SP/${package_name}.py"
        for candidate in "$MAIN_SP/${package_name}"*.so \
                         "$MAIN_SP/${package_name}"*.dist-info \
                         "$MAIN_SP/${package_name//_/-}"*.dist-info; do
            materialize_runtime_path "$candidate"
        done
    done
    for pattern in "${AMMO_TRACK_LOCAL_RUNTIME_EXTRA_GLOBS[@]}"; do
        for candidate in "$MAIN_SP"/$pattern; do
            materialize_runtime_path "$candidate"
        done
    done
    shopt -u nullglob

    # Replay PATH-STYLE .pth redirects from the main venv generically (content-driven,
    # not lib-specific). Some third-party libs expose their import name only via a
    # redirect .pth (e.g. nvidia_cutlass_dsl.pth points `cutlass` at a nested
    # python_packages/ dir). site.py only processes .pth files in dirs on sys.path at
    # startup; it does NOT recurse into a dir added by another .pth's path line — so
    # without this replay the worktree never gets those nested dirs on sys.path and
    # `import cutlass` (and any future redirect-style lib) fails.
    # SKIP `import `-directive / `;` (shim) lines: replaying them into main-venv.pth —
    # itself a processed .pth — would execute them at startup and load the editable-vllm
    # finder, breaking WorktreeFinder precedence.
    for pth in "$MAIN_SP"/*.pth; do
        [ -e "$pth" ] || continue
        # newline-safe: e.g. nvidia_cutlass_dsl.pth has NO trailing newline; the
        # `|| [ -n "$line" ]` guard emits the final unterminated line (proven required).
        while IFS= read -r line || [ -n "$line" ]; do
            [ -z "${line//[[:space:]]/}" ] && continue                 # skip empty / whitespace-only
            # Skip lines CPython site.py would exec(): `import ` / `import\t` directives,
            # and `;`-containing shim lines (defense-in-depth: keeps fragile lines out of
            # main-venv.pth so the editable-vllm finder never loads).
            case "$line" in import\ *|import$'\t'*|*\;*) continue ;; esac
            case "$line" in
                /*) resolved="$line" ;;
                *)  resolved="$MAIN_SP/$line" ;;                       # make relative lines absolute under MAIN_SP
            esac
            [ "$resolved" = "$MAIN_SP" ] && continue                   # don't duplicate MAIN_SP itself
            materialized_dst="$resolved"
            while IFS=$'\t' read -r materialized_src materialized_dst_candidate; do
                [ -z "${materialized_src:-}" ] && continue
                if [[ "$resolved" == "$materialized_src" || "$resolved" == "$materialized_src/"* ]]; then
                    materialized_dst="$materialized_dst_candidate${resolved#$materialized_src}"
                    break
                fi
            done < "$MATERIALIZED_ROOTS_FILE"
            if [ -d "$materialized_dst" ]; then
                echo "$materialized_dst" >> "$SITE_PKGS/main-venv.pth"
            elif [ -d "$resolved" ]; then                              # skip dangling targets
                echo "$resolved" >> "$SITE_PKGS/main-venv.pth"
            fi
        done < "$pth"
    done

    # Python isolation: use a meta-path finder to redirect `import vllm` to the
    # worktree. This is necessary because sys.path[0] = '' (CWD) is set by CPython
    # AFTER .pth files process, so sys.path.insert(0, ...) and plain .pth entries
    # both lose to CWD when CWD is the main repo. A meta-path finder intercepts
    # imports BEFORE PathFinder checks sys.path — same pattern as pip editable installs.
    cat > "$SITE_PKGS/_worktree_finder.py" << 'FINDER_EOF'
import sys
from importlib.util import spec_from_file_location
from pathlib import Path

WORKTREE_ROOT = '__WORKTREE_DIR__'
WORKTREE_PACKAGES = {'vllm'}

class WorktreeFinder:
    @classmethod
    def find_spec(cls, fullname, path=None, target=None):
        top_level = fullname.split('.')[0]
        if top_level not in WORKTREE_PACKAGES:
            return None
        if fullname in WORKTREE_PACKAGES:
            pkg_path = Path(WORKTREE_ROOT) / fullname
            init = pkg_path / '__init__.py'
            if init.exists():
                return spec_from_file_location(
                    fullname, str(init),
                    submodule_search_locations=[str(pkg_path)]
                )
        return None

def install():
    if not any(getattr(f, '__name__', '') == 'WorktreeFinder' for f in sys.meta_path):
        for i, finder in enumerate(sys.meta_path):
            if getattr(finder, '__name__', '') == 'PathFinder':
                sys.meta_path.insert(i, WorktreeFinder)
                return
        sys.meta_path.append(WorktreeFinder)
FINDER_EOF
    sed -i "s|__WORKTREE_DIR__|$WORKTREE_DIR|g" "$SITE_PKGS/_worktree_finder.py"

    # Install via .pth import directive (processed during site init)
    echo "import _worktree_finder; _worktree_finder.install()" > "$SITE_PKGS/worktree.pth"

    # Also add worktree to sys.path for non-vllm imports (test fixtures, scripts)
    echo "$WORKTREE_DIR" > "$SITE_PKGS/worktree-path.pth"

    # Create console script wrappers (thin venv has no pip-installed scripts)
    cat > "$WORKTREE_DIR/.venv/bin/vllm" << WRAPPER
#!/bin/bash
exec "\$(dirname "\$0")/python" -c "from vllm.entrypoints.cli.main import main; main()" "\$@"
WRAPPER
    chmod +x "$WORKTREE_DIR/.venv/bin/vllm"

    cat > "$WORKTREE_DIR/.venv/bin/pytest" << WRAPPER
#!/bin/bash
exec "\$(dirname "\$0")/python" -m pytest "\$@"
WRAPPER
    chmod +x "$WORKTREE_DIR/.venv/bin/pytest"

    echo "  .venv created (Python isolation active)" >&2
} || echo "  WARN: venv creation failed" >&2

echo "Worktree ready." >&2
echo "$WORKTREE_DIR"
