#!/bin/bash
set -euo pipefail

# WorktreeCreate hook for vLLM
# Creates a git worktree with build artifacts + Python isolation pre-populated.
#
# Input (stdin JSON): { session_id, transcript_path, cwd, hook_event_name, name }
# Output (stdout): absolute path to the created worktree directory
# All logging goes to stderr.

# ── Read hook input ──
INPUT=$(cat)
WORKTREE_NAME=$(echo "$INPUT" | jq -r '.name // empty')
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

[ -z "$WORKTREE_NAME" ] && { echo "ERROR: No worktree name provided" >&2; exit 1; }

MAIN_REPO="${CLAUDE_PROJECT_DIR:-$CWD}"
if [ -z "${CLAUDE_PROJECT_DIR:-}" ] && [ -f "$MAIN_REPO/.git" ]; then
    MAIN_REPO=$(git -C "$MAIN_REPO" rev-parse --path-format=absolute --git-common-dir 2>/dev/null | sed 's|/\.git$||')
fi

WORKTREE_DIR="$MAIN_REPO/.claude/worktrees/$WORKTREE_NAME"

# Guard: already exists
if [ -d "$WORKTREE_DIR" ]; then
    echo "WARN: Worktree already exists: $WORKTREE_DIR" >&2
    echo "$WORKTREE_DIR"
    exit 0
fi

# ── 1. Create git worktree (with flock for concurrency safety) ──
# Session-namespaced branch naming for cross-session safety
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
if [ -n "$SESSION_ID" ]; then
    BRANCH_NAME="session/${SESSION_ID}/ammo-${WORKTREE_NAME}"
else
    BRANCH_NAME="worktree-${WORKTREE_NAME}"
fi
mkdir -p "$MAIN_REPO/.claude/worktrees"

LOCKFILE="$MAIN_REPO/.claude/worktrees/.create-lock"
(
    flock -x 200
    echo "Creating worktree '$WORKTREE_NAME'..." >&2
    git -C "$MAIN_REPO" worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR" HEAD 2>&1 >&2 || \
        git -C "$MAIN_REPO" worktree add "$WORKTREE_DIR" "$BRANCH_NAME" 2>&1 >&2 || \
        git -C "$MAIN_REPO" worktree add "$WORKTREE_DIR" HEAD 2>&1 >&2 || {
            echo "ERROR: Failed to create worktree" >&2; exit 1
        }
) 200>"$LOCKFILE"
[ ! -d "$WORKTREE_DIR" ] && { echo "ERROR: Worktree creation failed" >&2; exit 1; }

# ── 2. Copy build artifacts ──
echo "Copying build artifacts..." >&2

# CMakeUserPresets.json (gitignored, needed for cmake --preset)
# Patch in CCACHE_PATH_MAP to remap worktree paths → main repo paths before hashing.
# Combined with CCACHE_BASEDIR=${sourceDir}, this gives 100% cross-worktree cache hits.
if [ -f "$MAIN_REPO/CMakeUserPresets.json" ]; then
    cp "$MAIN_REPO/CMakeUserPresets.json" "$WORKTREE_DIR/" 2>/dev/null
    # Inject CCACHE_PATH_MAP into the environment block
    if command -v jq &>/dev/null; then
        jq --arg pm "$WORKTREE_DIR:$MAIN_REPO" \
           '.configurePresets[0].environment.CCACHE_PATH_MAP = $pm' \
           "$WORKTREE_DIR/CMakeUserPresets.json" > "$WORKTREE_DIR/CMakeUserPresets.json.tmp" && \
           mv "$WORKTREE_DIR/CMakeUserPresets.json.tmp" "$WORKTREE_DIR/CMakeUserPresets.json"
    else
        echo "  WARN: jq not found, CCACHE_PATH_MAP not set (builds will be slow)" >&2
    fi
    echo "  CMakeUserPresets.json (with CCACHE_PATH_MAP)" >&2
fi

# All .so files under vllm/ (glob — automatically picks up new extensions)
find "$MAIN_REPO/vllm" -name "*.so" -type f 2>/dev/null | while read so; do
    REL="${so#$MAIN_REPO/}"
    mkdir -p "$(dirname "$WORKTREE_DIR/$REL")"
    cp "$so" "$WORKTREE_DIR/$REL" 2>/dev/null || true
done
echo "  .so files: $(find "$WORKTREE_DIR/vllm" -name '*.so' 2>/dev/null | wc -l) copied" >&2

# _version.py (generated by setuptools-scm, needed for `import vllm`)
[ -f "$MAIN_REPO/vllm/_version.py" ] && \
    cp "$MAIN_REPO/vllm/_version.py" "$WORKTREE_DIR/vllm/_version.py" 2>/dev/null && \
    echo "  vllm/_version.py" >&2 || true

# Other gitignored generated files (triton_kernels, grpc, csrc templates) are
# regenerated by `cmake --preset release` via FetchContent + install rules.

# No cmake-build-release/ copying needed — ccache with CCACHE_PATH_MAP (set in
# CMakeUserPresets.json above) provides 100% cross-worktree cache hits.
# The agent runs `cmake --preset release && cmake --build --preset release --target install`
# which takes ~50s configure + ~5s build (all ccache hits) on first use.

# ── 3. Create per-worktree .venv for Python isolation ──
echo "Creating worktree venv..." >&2
PY_VERSION=$("$MAIN_REPO/.venv/bin/python" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
"$MAIN_REPO/.venv/bin/python" -m venv --without-pip "$WORKTREE_DIR/.venv" 2>&1 >&2 && {
    SITE_PKGS="$WORKTREE_DIR/.venv/lib/python${PY_VERSION}/site-packages"

    # Add main venv packages (torch, numpy, etc.) via .pth
    # .pth files added via sys.path do NOT have their .pth files processed,
    # so the main venv's editable install meta_path finder is NOT loaded
    echo "$MAIN_REPO/.venv/lib/python${PY_VERSION}/site-packages" > "$SITE_PKGS/main-venv.pth"

    # Add worktree root so `import vllm` finds the worktree's vllm/ package
    echo "$WORKTREE_DIR" > "$SITE_PKGS/worktree.pth"

    # Create console script wrappers (thin venv has no pip-installed scripts)
    for cmd in pytest vllm; do
        cat > "$WORKTREE_DIR/.venv/bin/$cmd" << 'WRAPPER'
#!/bin/bash
exec "$(dirname "$0")/python" -m CMD_PLACEHOLDER "$@"
WRAPPER
        sed -i "s|CMD_PLACEHOLDER|$cmd|g" "$WORKTREE_DIR/.venv/bin/$cmd"
        chmod +x "$WORKTREE_DIR/.venv/bin/$cmd"
    done

    echo "  .venv created (Python isolation active)" >&2
} || echo "  WARN: venv creation failed" >&2

echo "Worktree ready." >&2
echo "$WORKTREE_DIR"
